/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-11 16:23:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addPatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<style>\n");
      out.write("  .required-mark { color: red; }\n");
      out.write("</style>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Add Patient</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  <h1>Add Patient</h1>\n");
      out.write("\n");
      out.write("  ");

    String errorMessage = (String) request.getAttribute("errorMessage");
    if (errorMessage != null) {
  
      out.write("\n");
      out.write("    <p style=\"color:red;\">");
      out.print( errorMessage );
      out.write("</p>\n");
      out.write("  ");

    }
  
      out.write("\n");
      out.write("\n");
      out.write("  <form method=\"post\" action=\"addPatient\">\n");
      out.write("    <!-- Names -->\n");
      out.write("    <label>Prefix:\n");
      out.write("          <input type=\"text\" name=\"PREFIX\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>First name <span class=\"required-mark\">*</span>:\n");
      out.write("      <input type=\"text\" name=\"FIRST\" required>\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>Last name <span class=\"required-mark\">*</span>:\n");
      out.write("      <input type=\"text\" name=\"LAST\" required>\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>Suffix:\n");
      out.write("          <input type=\"text\" name=\"SUFFIX\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Maiden name:\n");
      out.write("              <input type=\"text\" name=\"MAIDEN\">\n");
      out.write("            </label><br>\n");
      out.write("\n");
      out.write("    <!-- Basic demographics -->\n");
      out.write("    <label>Birthdate: (YYYY-MM-DD):\n");
      out.write("          <input type=\"text\" name=\"BIRTHDATE\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Deathdate: (YYYY-MM-DD):\n");
      out.write("          <input type=\"text\" name=\"DEATHDATE\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>SSN:\n");
      out.write("          <input type=\"text\" name=\"SSN\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Drivers Licence Number:\n");
      out.write("          <input type=\"text\" name=\"DRIVERS\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Passport Number:\n");
      out.write("          <input type=\"text\" name=\"PASSPORT\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Gender:\n");
      out.write("      <input type=\"text\" name=\"GENDER\">\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>Marital Status:\n");
      out.write("          <input type=\"text\" name=\"MARITAL\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Race:\n");
      out.write("          <input type=\"text\" name=\"RACE\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Ethnicity:\n");
      out.write("          <input type=\"text\" name=\"ETHNICITY\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("    <label>Birthplace:\n");
      out.write("          <input type=\"text\" name=\"BIRTHPLACE\">\n");
      out.write("        </label><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Address -->\n");
      out.write("    <label>Address:\n");
      out.write("      <input type=\"text\" name=\"ADDRESS\">\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>City:\n");
      out.write("      <input type=\"text\" name=\"CITY\">\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>State:\n");
      out.write("      <input type=\"text\" name=\"STATE\">\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("    <label>ZIP:\n");
      out.write("      <input type=\"text\" name=\"ZIP\">\n");
      out.write("    </label><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <input type=\"submit\" value=\"Add Patient\">\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
